export const productActualPrice = "IF(isFixedPrice,p.fixed_price,(IF(p.pmt_id > 0,IF(p.pmt_id < 10,(pr.purity / 100 * gold.price / 11.664 * p.weight) +(p.mk_pp + p.mk_gm +(p.jarti / 100) * gold.price / 11.664 * p.weight),IF(p.pmt_id = 11,(4 * silver.price * p.weight / 11.664),(pr.purity / 100 * silver.price / 11.664 * p.weight) +(p.mk_pp + p.mk_gm +(p.jarti / 100) * silver.price / 11.664 * p.weight))),0) +(IF(p.p_name LIKE '%solitaire%',p.dc_rate,dia.price) * dc_qty + p.dc_rate_bce2 * p.dc_qty_bce2)))";

export const productDiscount = "IF(isFixedPrice,p.fixed_price * p.offer / 100,(IF(p.pmt_id > 0,IF(p.pmt_id < 10,(pr.purity / 100 * gold.price / 11.664 * p.weight) +(p.mk_pp + p.mk_gm +(p.jarti / 100) * gold.price / 11.664 * p.weight),IF(p.pmt_id = 11,0,(pr.purity / 100 * silver.price / 11.664 * p.weight) +(p.mk_pp + p.mk_gm +(p.jarti / 100) * silver.price / 11.664 * p.weight))),0)) * p.offer / 100 +(dia.discount / 100 *(IF(p.p_name LIKE '%solitaire%',p.dc_rate,dia.price) * dc_qty + p.dc_rate_bce2 * p.dc_qty_bce2) + IF(p.pmt_id = 11,(0.5 * silver.price * p.weight / 11.664),0) ))";

export const productFinalPrice = productActualPrice + " - " + productDiscount;

export const sqlProductFetch = (columns="") =>{

const sql = "SELECT p.id_pack AS id," + columns + " IF( p.image <> '',p.image,( SELECT ps.s_path FROM package_slider ps WHERE ps.id_pack = p.id_pack LIMIT 1)) AS image,"+ productActualPrice +" AS dynamic_price,"+ productDiscount +" AS discount,"+ productFinalPrice +" AS final_price,IF(isFixedPrice,p.fixed_price,(IF(p.pmt_id > 0,IF(p.pmt_id < 10,(pr.purity / 100 * gold.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti_b2b / 100) * gold.price / 11.664 * p.weight),IF(p.pmt_id = 11,(2.5 * silver.price * p.weight / 11.664),(pr.purity / 100 * silver.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti / 100) * silver.price / 11.664 * p.weight))),0 ) +(IF(p.p_name LIKE '%solitaire%',p.dc_rate,dia.price * .75) * dc_qty + p.dc_rate_b2b_b2e2 * p.dc_qty_b2b_b2e2) )) AS actual_price_b2b, IF( isFixedPrice, p.fixed_price * p.offer_b2b / 100, (IF(p.pmt_id > 0,IF(p.pmt_id < 10,(pr.purity / 100 * gold.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti_b2b / 100) * gold.price / 11.664 * p.weight),IF(p.pmt_id = 11,0,(pr.purity / 100 * silver.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti_b2b / 100) * silver.price / 11.664 * p.weight))),0)) * p.offer_b2b / 100 +(dia.discount / 100 *(IF(p.p_name LIKE '%solitaire%',p.dc_rate,dia.price * .75) * dc_qty + p.dc_rate_b2b_b2e2 * p.dc_qty_b2b_b2e2) + IF(p.pmt_id = 11,(0.7 * silver.price * p.weight / 11.664),0))) AS discount_b2b, (IF(isFixedPrice,p.fixed_price,(IF(p.pmt_id > 0,IF(p.pmt_id < 10,(pr.purity / 100 * gold.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti_b2b / 100) * gold.price / 11.664 * p.weight),IF(p.pmt_id = 11,(2.5 * silver.price * p.weight / 11.664),(pr.purity / 100 * silver.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti / 100) * silver.price / 11.664 * p.weight))),0) +(IF(p.p_name LIKE '%solitaire%',p.dc_rate,dia.price * .75) * dc_qty + p.dc_rate_b2b_b2e2 * p.dc_qty_b2b_b2e2))) ) - (IF(isFixedPrice,p.fixed_price * p.offer_b2b / 100,(IF(p.pmt_id > 0,IF(p.pmt_id < 10,(pr.purity / 100 * gold.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti_b2b / 100) * gold.price / 11.664 * p.weight),IF(p.pmt_id = 11,0,(pr.purity / 100 * silver.price / 11.664 * p.weight) +(p.mk_pp_b2b + p.mk_gm_b2b +(p.jarti_b2b / 100) * silver.price / 11.664 * p.weight))),0)) * p.offer_b2b / 100 +(dia.discount / 100 *(IF(p.p_name LIKE '%solitaire%',p.dc_rate,dia.price * .75) * dc_qty + p.dc_rate_b2b_b2e2 * p.dc_qty_b2b_b2e2 ) + IF(p.pmt_id = 11,(0.7 * silver.price * p.weight / 11.664),0))) ) AS final_price_b2b FROM package p JOIN package_metal pr ON p.pmt_id = pr.pmt_id JOIN package_material pm ON p.pm_id = pm.pm_id JOIN package_material dia ON dia.pm_id = 1 JOIN package_material gold ON gold.pm_id = 2 JOIN package_material silver ON silver.pm_id = 3 "

return sql

}